# Auto-generated by src/build_submit.py — do not edit by hand.
import os, sys, json, warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import joblib
import lightgbm as lgb
from scipy.special import expit, logit, softmax

# ===== features.py =====
"""Feature engineering.
import warnings; warnings.filterwarnings("ignore")

Two stages so that validation and inference share identical code paths:
  1. build_stats(train_df): per-(pitcher, season) / per-(batter, season) totals computed
     from official training rows only (seasons < val season for validation, all seasons for test).
  2. build_features(df, stats): per-row features using ONLY the row's own columns + stats.
     No cross-row information from `df` is used (rule: each test row predicted independently).

Key insight: asof_* rates are exact cumulative means over the entity's whole history (2019-),
so  cur_count = asof_n - prior_seasons_count  and  cur_success = asof_n*asof_rate - prior_success
recover the entity's *current-season-to-date* record exactly from a single row.
"""
import os

RATE_COLS_P = {  # asof rate column -> short name (all share denominator asof_pitcher_n)
    'asof_pitcher_success_rate': 's', 'asof_pitcher_reverse_rate': 'rev',
    'asof_pitcher_middle_rate': 'mid', 'asof_pitcher_ball_rate': 'ball',
    'asof_pitcher_strike_rate': 'strike', 'asof_pitcher_fastball_rate': 'fb',
    'asof_pitcher_breaking_rate': 'br', 'asof_pitcher_offspeed_rate': 'os',
}
RATE_COLS_B = {'asof_batter_success_rate': 's', 'asof_batter_middle_rate': 'mid'}
P_KEYS = list(RATE_COLS_P.values())
B_KEYS = list(RATE_COLS_B.values())
MAX_SEASON = 2026


def _recover_indicators(df, id_col, n_col, rate_cols, target='control_success'):
    """Recover per-pitch 0/1 indicators from consecutive cumulative rates (sorted by id, row order).
    The entity's final pitch has no successor -> imputed with expectations."""
    d = df[[id_col, n_col, target] + list(rate_cols)].copy()
    d['_ord'] = np.arange(len(d))
    d = d.sort_values([id_col, '_ord'])
    n = d[n_col].values.astype(float)
    out = {}
    nxt_id_same = (d[id_col].shift(-1) == d[id_col]).values
    for c, k in rate_cols.items():
        cum = np.nan_to_num(d[c].values * n)          # count through previous pitch
        cum_next = np.roll(cum, -1)
        ind = np.where(nxt_id_same, np.rint(cum_next - cum), np.nan)
        out[k] = ind
    res = pd.DataFrame(out, index=d.index)
    # impute final pitch of each entity
    y = d[target].values.astype(float)
    last = ~nxt_id_same
    for k in res.columns:
        col = res[k].values
        if k == 's':
            col[last] = y[last]
        elif k in ('rev', 'mid'):
            # failure modes: 0 if success; else conditional expectation given failure
            r = np.nan_to_num(d[[c for c, kk in rate_cols.items() if kk == k][0]].values[last])
            sr = np.nan_to_num(d['asof_pitcher_success_rate'].values[last]) if 'asof_pitcher_success_rate' in d else 0.52
            cond = np.clip(r / np.clip(1 - sr, 1e-3, None), 0, 1)
            col[last] = np.where(y[last] == 1, 0.0, cond)
        else:
            r = np.nan_to_num(d[[c for c, kk in rate_cols.items() if kk == k][0]].values[last])
            col[last] = r
        res[k] = col
    return res.sort_index()


def build_stats_v1(train):
    """Per-(entity, season) totals from training rows."""
    tr = train.reset_index(drop=True)
    pind = _recover_indicators(tr, 'pitcher_id', 'asof_pitcher_n', RATE_COLS_P)
    bind = _recover_indicators(tr, 'batter_id', 'asof_batter_n', RATE_COLS_B)
    p = pd.DataFrame({'pitcher_id': tr.pitcher_id, 'season': tr.season, 'n': 1.0})
    for k in P_KEYS:
        p[k] = pind[k].values
    p['n_F'] = (tr.game_type == 'F').astype(float)
    p['n_LG'] = ((tr.game_type == 'R') & ((tr.pitcher_team_id == 13) | (tr.batter_team_id == 13))).astype(float)   # LG-involved R pitches (label-source regime)
    p['s_LG'] = p['n_LG'] * tr.control_success
    p['n_new'] = (tr.season >= 2023).astype(float); p['s_new'] = p['n_new'] * tr.control_success   # new label regime (2023+) pitches
    p['s_F'] = p['n_F'] * tr.control_success
    p['n_L'] = (tr.batter_hand == 1).astype(float)   # vs batter_hand==1
    p['s_L'] = p['n_L'] * tr.control_success
    p['n_2k'] = (tr.strikes_before == 2).astype(float)   # two-strike counts
    p['s_2k'] = p['n_2k'] * tr.control_success
    p['n_00'] = ((tr.balls_before == 0) & (tr.strikes_before == 0)).astype(float)   # first pitch of PA
    p['s_00'] = p['n_00'] * tr.control_success
    p['n_late'] = (tr.inning >= 7).astype(float); p['s_late'] = p['n_late'] * tr.control_success
    p['n_L2k'] = ((tr.batter_hand == 1) & (tr.strikes_before == 2)).astype(float); p['s_L2k'] = p['n_L2k'] * tr.control_success
    p['rev_L'] = p['n_L'] * p['rev']; p['mid_L'] = p['n_L'] * p['mid']   # class-specific platoon sums
    for k in ('fb', 'br', 'os'):  # pitch-type-specific successes (type recovered from cumulative mix rates)
        p['s_' + k] = p[k] * tr.control_success
    new_regime = (tr.season >= 2023).astype(float)  # Futures measurement regime changed in 2023
    p['n_F23'] = p['n_F'] * new_regime; p['s_F23'] = p['s_F'] * new_regime
    ps = p.groupby(['pitcher_id', 'season']).sum().reset_index()
    b = pd.DataFrame({'batter_id': tr.batter_id, 'season': tr.season, 'n': 1.0})
    for k in B_KEYS:
        b[k] = bind[k].values
    b['n_F'] = (tr.game_type == 'F').astype(float)
    b['s_F'] = b['n_F'] * tr.control_success
    bs = b.groupby(['batter_id', 'season']).sum().reset_index()
    # pitcher x batter matchup per season
    pb = pd.DataFrame({'pb_key': tr.pitcher_id.values.astype(np.int64) * 100000 + tr.batter_id.values.astype(np.int64), 'season': tr.season, 'n': 1.0, 's': tr.control_success.astype(float)})
    pbs = pb.groupby(['pb_key', 'season']).sum().reset_index()
    # league-level per-season rate (for drift-aware priors)
    league = tr.groupby('season').control_success.agg(['mean', 'size']).reset_index()
    league.columns = ['season', 'league_rate', 'league_n']
    # label-source effects per season: LG-involved R / non-LG R / F, relative to the pooled league mean
    lg_r = (tr.game_type == 'R') & ((tr.pitcher_team_id == 13) | (tr.batter_team_id == 13)); f_ = tr.game_type == 'F'
    src = pd.DataFrame({'season': tr.season.values, 'y': tr.control_success.values.astype(float), 'src': np.where(f_, 'F', np.where(lg_r, 'LG', 'B'))})
    lm = src.groupby('season').y.mean(); se = src.groupby(['season', 'src']).y.mean().unstack('src').reindex(columns=['LG', 'B', 'F'])
    src_eff = pd.DataFrame({'eff_LG': se['LG'] - lm, 'eff_B': se['B'] - lm, 'eff_F': se['F'] - lm}).fillna(0.0)
    return {'ps': ps, 'bs': bs, 'pbs': pbs, 'league': league, 'max_season': int(tr.season.max()), 'src_eff': src_eff}


def _prior_table(tab, id_col, cols, max_season=MAX_SEASON, last_col='s'):
    """For each (id, season y) in a dense grid: sums over seasons < y, plus last-active-season info."""
    ids = tab[id_col].unique()
    seasons = np.arange(tab.season.min(), max_season + 1)
    grid = pd.MultiIndex.from_product([ids, seasons], names=[id_col, 'season'])
    t = tab.set_index([id_col, 'season']).reindex(grid).fillna(0.0)
    wide = {c: t[c].unstack('season') for c in cols}
    prior = {}
    for c in cols:
        cs = wide[c].cumsum(axis=1).shift(1, axis=1).fillna(0.0)
        prior['prior_' + c] = cs
    # last active season stats (n, s) and gap
    n_w = wide['n']
    act = n_w.gt(0)
    seas = pd.DataFrame(np.tile(seasons, (len(ids), 1)), index=n_w.index, columns=n_w.columns)
    last_seas = seas.where(act).ffill(axis=1).shift(1, axis=1)
    last_n = n_w.where(act).ffill(axis=1).shift(1, axis=1)
    last_s = wide[last_col].where(act).ffill(axis=1).shift(1, axis=1)
    prior['last_season_gap'] = seas - last_seas
    prior['last_n'] = last_n
    prior['last_s'] = last_s
    prior['n_seasons'] = act.astype(float).cumsum(axis=1).shift(1, axis=1).fillna(0.0)
    out = pd.concat({k: v.stack(dropna=False) for k, v in prior.items()}, axis=1).reset_index()
    return out



def _weighted_prior(tab, id_col, cols, decay, max_season=MAX_SEASON):
    """Recency-weighted sums over seasons < y: sum_k w^(y-1-k) * x_k (w=decay). Returns frame keyed by (id, season)."""
    ids = tab[id_col].unique(); seasons = np.arange(tab.season.min(), max_season + 1)
    grid = pd.MultiIndex.from_product([ids, seasons], names=[id_col, 'season'])
    t = tab.set_index([id_col, 'season']).reindex(grid).fillna(0.0)
    out = {}
    for c in cols:
        w = t[c].unstack('season'); acc = np.zeros(len(w)); res = np.zeros((len(w), len(seasons)))
        for j, y in enumerate(seasons):
            res[:, j] = acc; acc = decay * acc + w[y].values
        out['wprior_' + c] = pd.DataFrame(res, index=w.index, columns=pd.Index(seasons, name='season')).stack()
    return pd.concat(out, axis=1).reset_index()


def build_features_v1(df, stats, league_prior=None):
    """Row-wise features. df: train or test rows (any seasons). Only own columns + stats used."""
    d = df.copy()
    ps, bs = stats['ps'], stats['bs']
    P_COLS = ['n'] + P_KEYS + ['n_F', 's_F', 'n_L', 's_L', 's_fb', 's_br', 's_os', 'n_F23', 's_F23'] + (['n_2k', 's_2k'] if 'n_2k' in ps.columns else []) + (['n_00', 's_00'] if 'n_00' in ps.columns else []) + (['n_late', 's_late', 'n_L2k', 's_L2k'] if 'n_late' in ps.columns else []) + (['rev_L', 'mid_L'] if 'rev_L' in ps.columns else []) + (['n_new', 's_new', 'n_LG', 's_LG'] if 'n_new' in ps.columns else [])
    B_COLS = ['n'] + B_KEYS + ['n_F', 's_F']
    pp = _prior_table(ps, 'pitcher_id', P_COLS)
    bp = _prior_table(bs, 'batter_id', B_COLS)
    d = d.merge(pp, on=['pitcher_id', 'season'], how='left')
    d = d.merge(bp.rename(columns={c: 'b' + c for c in bp.columns if c not in ('batter_id', 'season')}),
                on=['batter_id', 'season'], how='left')
    for c in pp.columns:
        if c.startswith('prior_') or c == 'n_seasons':
            d[c] = d[c].fillna(0.0)
    for c in bp.columns:
        if c.startswith('prior_') or c == 'n_seasons':
            d['b' + c] = d['b' + c].fillna(0.0)

    F = pd.DataFrame(index=d.index)
    # ---------- raw situational ----------
    F['season'] = d.season
    F['game_month'] = d.game_month
    F['game_dow'] = d.game_dayofweek
    F['inning'] = d.inning
    F['is_top'] = (d.top_bottom == 'T').astype(int)
    F['game_type_F'] = (d.game_type == 'F').astype(int)
    F['balls'] = d.balls_before
    F['strikes'] = d.strikes_before
    F['count_state'] = d.balls_before * 3 + d.strikes_before
    F['outs'] = d.outs_before
    F['run_top'] = d.run_top_before
    F['run_bot'] = d.run_bot_before
    F['run_total'] = d.run_total_before
    F['score_diff_home'] = d.score_diff_home
    F['score_diff_p'] = d.score_diff_pitcher_team
    F['abs_score_diff'] = d.score_diff_pitcher_team.abs()
    F['r1'] = d.runner_on_1b; F['r2'] = d.runner_on_2b; F['r3'] = d.runner_on_3b
    F['n_runners'] = d.num_runners_on
    F['base_state'] = d.base_state.map({'___': 0, '1__': 1, '_2_': 2, '__3': 3, '12_': 4, '1_3': 5, '_23': 6, '123': 7}).astype(int)
    F['home_we'] = d.home_win_expectancy
    F['pitcher_we'] = np.where(d.top_bottom == 'T', d.home_win_expectancy, d.away_win_expectancy)
    F['li'] = d.li
    F['pitcher_hand'] = d.pitcher_hand
    F['batter_hand'] = d.batter_hand
    F['platoon_same'] = (d.pitcher_hand == d.batter_hand).astype(int)
    F['pitcher_team'] = d.pitcher_team_id
    F['batter_team'] = d.batter_team_id
    F['pitcher_id'] = d.pitcher_id
    F['batter_id'] = d.batter_id
    # ---------- raw asof ----------
    F['asof_p_n'] = d.asof_pitcher_n
    for c in RATE_COLS_P:
        F[c.replace('asof_pitcher_', 'asof_p_')] = d[c]
    for c in ['asof_pitcher_prev1_game_success_rate', 'asof_pitcher_prev3_game_success_rate',
              'asof_pitcher_prev5_game_success_rate', 'asof_pitcher_prev1_game_middle_rate',
              'asof_pitcher_prev3_game_middle_rate', 'asof_pitcher_prev5_game_middle_rate']:
        F[c.replace('asof_pitcher_', 'asof_p_')] = d[c]
    F['asof_b_n'] = d.asof_batter_n
    for c in RATE_COLS_B:
        F[c.replace('asof_batter_', 'asof_b_')] = d[c]
    # ---------- decomposition: current-season-to-date (cur) vs prior seasons ----------
    pn = d.asof_pitcher_n.values.astype(float)
    F['p_prior_n'] = d.prior_n
    F['p_cur_n'] = np.clip(pn - d.prior_n.values, 0, None)
    cur_n = F['p_cur_n'].values
    for c, k in RATE_COLS_P.items():
        tot = np.nan_to_num(d[c].values * pn)
        cur = tot - d['prior_' + k].values
        with np.errstate(invalid='ignore', divide='ignore'):
            F['p_cur_' + k + '_rate'] = np.where(cur_n > 0, cur / np.maximum(cur_n, 1), np.nan)
            F['p_prior_' + k + '_rate'] = np.where(d.prior_n.values > 0, d['prior_' + k].values / np.maximum(d.prior_n.values, 1), np.nan)
    F['p_cur_s'] = np.nan_to_num(d.asof_pitcher_success_rate.values * pn) - d.prior_s.values
    with np.errstate(invalid='ignore', divide='ignore'):
        F['p_prior_F_share'] = np.where(d.prior_n > 0, d.prior_n_F / d.prior_n, np.nan)
        F['p_prior_F_rate'] = np.where(d.prior_n_F > 0, d.prior_s_F / d.prior_n_F, np.nan)
        F['p_prior_F23_n'] = d.prior_n_F23
        F['p_prior_F23_rate'] = np.where(d.prior_n_F23 >= 20, d.prior_s_F23 / np.maximum(d.prior_n_F23, 1), np.nan)
        F['p_prior_F23_share'] = np.where(d.prior_n > 0, d.prior_n_F23 / np.maximum(d.prior_n, 1), np.nan)
        F['p_prior_R_rate'] = np.where(d.prior_n - d.prior_n_F > 0, (d.prior_s - d.prior_s_F) / (d.prior_n - d.prior_n_F), np.nan)
        F['p_prior_vsL_rate'] = np.where(d.prior_n_L > 0, d.prior_s_L / d.prior_n_L, np.nan)
        F['p_prior_vsR_rate'] = np.where(d.prior_n - d.prior_n_L > 0, (d.prior_s - d.prior_s_L) / (d.prior_n - d.prior_n_L), np.nan)
        F['p_prior_vsHand_rate'] = np.where(d.batter_hand == 1, F['p_prior_vsL_rate'], F['p_prior_vsR_rate'])
        # context-differential priors (shrunk, prior seasons): platoon (vs current batter hand) and two-strike trait
        def _shr_diff(s1, n1, s0, n0, K=1000.0):
            with np.errstate(invalid='ignore', divide='ignore'):
                m1 = s1 / np.maximum(n1, 1); m0 = s0 / np.maximum(n0, 1)
                ne = 1.0 / (1.0 / np.maximum(n1, 1) + 1.0 / np.maximum(n0, 1))
                return np.where((n1 > 0) & (n0 > 0), (m1 - m0) * ne / (ne + K), 0.0)
        pn_, ps_ = d.prior_n.values, d.prior_s.values
        isL = (d.batter_hand.values == 1)
        n1 = np.where(isL, d.prior_n_L.values, pn_ - d.prior_n_L.values); s1 = np.where(isL, d.prior_s_L.values, ps_ - d.prior_s_L.values)
        F['CTX_hand_diff'] = _shr_diff(s1, n1, ps_ - s1, pn_ - n1)
        F['CTX_hand_adj'] = F['CTX_hand_diff'].values * np.where(pn_ > 0, (pn_ - n1) / np.maximum(pn_, 1), 0.5)
        n2 = d.prior_n_2k.values if 'prior_n_2k' in d.columns else np.zeros(len(d)); s2 = d.prior_s_2k.values if 'prior_s_2k' in d.columns else np.zeros(len(d))
        d2 = _shr_diff(s2, n2, ps_ - s2, pn_ - n2); sh2 = np.where(pn_ > 0, n2 / np.maximum(pn_, 1), 0.28)
        F['CTX_2k_diff'] = d2
        F['CTX_2k_adj'] = np.where(d.strikes_before.values == 2, d2 * (1 - sh2), -d2 * sh2)
        if 'prior_n_late' in d.columns and os.environ.get('CTX_V3') == '1':
            K3 = float(os.environ.get('CTX_K', '1000'))
            # recency-weighted platoon differential
            wp = _weighted_prior(ps, 'pitcher_id', ['n', 's', 'n_L', 's_L'], float(os.environ.get('CTX_DECAY', '0.6')))
            dw = d[['pitcher_id', 'season']].merge(wp, on=['pitcher_id', 'season'], how='left').fillna(0.0)
            wn, ws_ = dw.wprior_n.values, dw.wprior_s.values; wnL, wsL = dw.wprior_n_L.values, dw.wprior_s_L.values
            n1w = np.where(isL, wnL, wn - wnL); s1w = np.where(isL, wsL, ws_ - wsL)
            F['CTX_hand_diff_w'] = _shr_diff(s1w, n1w, ws_ - s1w, wn - n1w, K=K3)
            F['CTX_hand_adj_w'] = F['CTX_hand_diff_w'].values * np.where(wn > 0, (wn - n1w) / np.maximum(wn, 1e-9), 0.5)
            # late-inning (>=7) differential
            nl, sl = d.prior_n_late.values, d.prior_s_late.values
            dl = _shr_diff(sl, nl, ps_ - sl, pn_ - nl, K=K3); shl = np.where(pn_ > 0, nl / np.maximum(pn_, 1), 0.33)
            F['CTX_late_diff'] = dl
            F['CTX_late_adj'] = np.where(d.inning.values >= 7, dl * (1 - shl), -dl * shl)
            # LHB & two-strike cell vs rest
            nc, sc_ = d.prior_n_L2k.values, d.prior_s_L2k.values
            dc = _shr_diff(sc_, nc, ps_ - sc_, pn_ - nc, K=K3); shc = np.where(pn_ > 0, nc / np.maximum(pn_, 1), 0.13)
            F['CTX_L2k_diff'] = dc
            F['CTX_L2k_adj'] = np.where(isL & (d.strikes_before.values == 2), dc * (1 - shc), -dc * shc)
        if 'prior_n_new' in d.columns and os.environ.get('LGNEW') == '1':
            # regime-consistent priors: pitcher's rate/share in the 2023+ label regime, and share of old-regime LG pitches in history
            nn_, sn_ = d.prior_n_new.values, d.prior_s_new.values
            F['p_prior_new_n'] = nn_
            F['p_prior_new_rate'] = np.where(nn_ >= 30, sn_ / np.maximum(nn_, 1), np.nan)
            F['p_prior_new_share'] = np.where(pn_ > 0, nn_ / np.maximum(pn_, 1), np.nan)
            old_lg = (d.prior_n_LG.values + d.prior_n_F.values) - (nn_ * 0)  # LG-involved (R) + F pitches, all regimes
            F['p_prior_LG_share'] = np.where(pn_ > 0, old_lg / np.maximum(pn_, 1), np.nan)
        if 'prior_rev_L' in d.columns and os.environ.get('CTX_CLS') == '1':
            # class-specific platoon differentials (reverse / middle rate vs current hand minus other hand)
            for cls_, tot_ in (('rev', 'prior_rev'), ('mid', 'prior_mid')):
                cL = d['prior_' + cls_ + '_L'].values; cT = d[tot_].values
                c1 = np.where(isL, cL, cT - cL)
                F['CTX_hand_' + cls_ + '_diff'] = _shr_diff(c1, n1, cT - c1, pn_ - n1, K=float(os.environ.get('CTX_K', '1000')))
        if 'prior_n_00' in d.columns and os.environ.get('CTX_V2') == '1':
            n0_, s0_ = d.prior_n_00.values, d.prior_s_00.values
            d0 = _shr_diff(s0_, n0_, ps_ - s0_, pn_ - n0_); sh0 = np.where(pn_ > 0, n0_ / np.maximum(pn_, 1), 0.26)
            F['CTX_00_diff'] = d0
            F['CTX_00_adj'] = np.where((d.balls_before.values == 0) & (d.strikes_before.values == 0), d0 * (1 - sh0), -d0 * sh0)
        F['p_last_n'] = d.last_n
        F['p_last_rate'] = np.where(d.last_n > 0, d.last_s / d.last_n, np.nan)
    F['p_last_gap'] = d.last_season_gap
    F['p_n_seasons'] = d.n_seasons
    # pitch-type-specific prior success rates and mix-weighted expected rate
    with np.errstate(invalid='ignore', divide='ignore'):
        base = F['p_prior_s_rate'].values
        mix_exp = np.zeros(len(d)); wsum = np.zeros(len(d))
        for k in ('fb', 'br', 'os'):
            nk = d['prior_' + k].values; sk = d['prior_s_' + k].values
            F['p_prior_srate_' + k] = np.where(nk >= 30, sk / np.maximum(nk, 1), np.nan)
            shr = (sk + 100 * np.nan_to_num(base, nan=0.52)) / (nk + 100)
            mix = F['p_cur_' + k + '_rate'].values
            mix = np.where(np.isnan(mix), np.where(d.prior_n.values > 0, nk / np.maximum(d.prior_n.values, 1), np.nan), mix)
            mix = np.clip(np.nan_to_num(mix, nan=0.0), 0, 1)
            mix_exp += mix * shr; wsum += mix
        F['p_mix_exp_rate'] = np.where(wsum > 0, mix_exp / np.maximum(wsum, 1e-9), np.nan)
        F['p_mix_exp_minus_prior'] = F['p_mix_exp_rate'] - base
    # batter
    bn = d.asof_batter_n.values.astype(float)
    F['b_prior_n'] = d.bprior_n
    F['b_cur_n'] = np.clip(bn - d.bprior_n.values, 0, None)
    bcur_n = F['b_cur_n'].values
    for c, k in RATE_COLS_B.items():
        tot = np.nan_to_num(d[c].values * bn)
        cur = tot - d['bprior_' + k].values
        with np.errstate(invalid='ignore', divide='ignore'):
            F['b_cur_' + k + '_rate'] = np.where(bcur_n > 0, cur / np.maximum(bcur_n, 1), np.nan)
            F['b_prior_' + k + '_rate'] = np.where(d.bprior_n.values > 0, d['bprior_' + k].values / np.maximum(d.bprior_n.values, 1), np.nan)
    with np.errstate(invalid='ignore', divide='ignore'):
        F['b_last_rate'] = np.where(d.blast_n > 0, d.blast_s / d.blast_n, np.nan)
        F['b_last_n'] = d.blast_n
    F['b_last_gap'] = d.blast_season_gap
    F['b_n_seasons'] = d.bn_seasons
    # ---------- shrunken estimates ----------
    lp = 0.52 if league_prior is None else league_prior
    p_prior_rate = F['p_prior_s_rate'].fillna(lp).values
    for K in (100, 500):
        F[f'p_cur_s_shr{K}'] = (np.nan_to_num(F['p_cur_s'].values) + K * p_prior_rate) / (cur_n + K)
    F['p_all_s_shr200'] = (np.nan_to_num(d.asof_pitcher_success_rate.values * pn) + 200 * lp) / (pn + 200)
    b_prior_rate = F['b_prior_s_rate'].fillna(lp).values
    b_cur_s = np.nan_to_num(d.asof_batter_success_rate.values * bn) - d.bprior_s.values
    F['b_cur_s_shr300'] = (b_cur_s + 300 * b_prior_rate) / (bcur_n + 300)
    F['b_all_s_shr300'] = (np.nan_to_num(d.asof_batter_success_rate.values * bn) + 300 * lp) / (bn + 300)
    return F


CAT_FEATURES = ['pitcher_team', 'batter_team', 'base_state', 'count_state']


def add_change_features(F):
    """Relative (drift-aware) features: current-season-to-date vs prior seasons / last season."""
    F = F.copy()
    F['p_chg_s'] = F['p_cur_s_rate'] - F['p_prior_s_rate']
    F['p_chg_s_last'] = F['p_cur_s_rate'] - F['p_last_rate']
    F['b_chg_s'] = F['b_cur_s_rate'] - F['b_prior_s_rate']
    F['b_chg_s_last'] = F['b_cur_s_rate'] - F['b_last_rate']
    F['p_chg_rev'] = F['p_cur_rev_rate'] - F['p_prior_rev_rate']
    F['p_chg_mid'] = F['p_cur_mid_rate'] - F['p_prior_mid_rate']
    F['b_chg_mid'] = F['b_cur_mid_rate'] - F['b_prior_mid_rate']
    # precision-weighted combined drift estimate from the row's two entities
    wp = F['p_cur_n'] / (F['p_cur_n'] + 200.0)
    wb = F['b_cur_n'] / (F['b_cur_n'] + 200.0)
    cp = F['p_chg_s'].fillna(0.0) * wp
    cb = F['b_chg_s'].fillna(0.0) * wb
    F['drift_est'] = (cp + cb) / (wp + wb + 1e-6)
    F['p_cur_logn'] = np.log1p(F['p_cur_n'])
    F['b_cur_logn'] = np.log1p(F['b_cur_n'])
    # recent form vs season-to-date / prior
    F['p_form1'] = F['asof_p_prev1_game_success_rate'] - F['p_cur_s_rate']
    F['p_form3'] = F['asof_p_prev3_game_success_rate'] - F['p_cur_s_rate']
    F['p_form5'] = F['asof_p_prev5_game_success_rate'] - F['p_cur_s_rate']
    F['p_form5_prior'] = F['asof_p_prev5_game_success_rate'] - F['p_prior_s_rate']
    F['p_form_mid5'] = F['asof_p_prev5_game_middle_rate'] - F['p_cur_mid_rate']
    F['p_form_trend'] = F['asof_p_prev1_game_success_rate'] - F['asof_p_prev5_game_success_rate']
    return F


def add_matchup_features(F, df, stats):
    """Pitcher x batter matchup priors from training seasons < row season (row's own ids + train stats)."""
    pbs = stats.get('pbs')
    if pbs is None: return F
    d = pd.DataFrame({'pb_key': df.pitcher_id.values.astype(np.int64) * 100000 + df.batter_id.values.astype(np.int64), 'season': df.season.values})
    # restrict grid to keys present in df to keep it small
    keys = np.unique(d.pb_key.values)
    sub = pbs[pbs.pb_key.isin(keys)]
    if len(sub) == 0:
        # no training history for any pair in this frame: fall through with zero counts so that every formula below is evaluated
        # with exactly the same floating-point arithmetic as for n=0 rows in the general path (the NN's quantile transform is
        # sensitive to the ~1e-16 residue of (30*base)/30 - base, so the value must NOT be simplified to a literal 0.0)
        n = np.zeros(len(d)); sv = np.zeros(len(d))
    else:
        pt = _prior_table(sub, 'pb_key', ['n', 's'])[['pb_key', 'season', 'prior_n', 'prior_s']]
        d = d.merge(pt, on=['pb_key', 'season'], how='left')
        n = d.prior_n.fillna(0.0).values; sv = d.prior_s.fillna(0.0).values
    F['pb_prior_n'] = n
    with np.errstate(invalid='ignore', divide='ignore'):
        F['pb_prior_rate'] = np.where(n >= 10, sv / np.maximum(n, 1), np.nan)
        base = F['p_prior_s_rate'].fillna(0.52).values
        F['pb_prior_shr30'] = (sv + 30 * base) / (n + 30)
        F['pb_prior_dev'] = F['pb_prior_shr30'] - base
    return F
# ===== trackman_feats.py =====
"""Trackman pitcher-season profile table (via matched IDs) + role stats helpers."""
import warnings; warnings.filterwarnings("ignore")

TM_METRICS = ['rel_speed', 'spin_rate', 'induced_vert_break', 'horz_break', 'extension', 'rel_height', 'rel_side', 'zone_speed']
TYPES = ['Fastball', 'Slider', 'Curveball', 'ChangeUp', 'Splitter', 'Sinker', 'Cutter']


def build_tm_table(pmap_path=None):
    tm = load_trackman()
    pmap = pd.read_parquet(pmap_path or os.path.join(ROOT, 'data', 'derived', 'pitcher_map.parquet'))
    pmap = pmap[(pmap.purity > 0.9) & (pmap.votes >= 30)]
    tm = tm.merge(pmap[['pitcher_id', 'tm_id']].rename(columns={'tm_id': 'pitcher_trackman_id'}), on='pitcher_trackman_id')
    tm['ChangeUp'] = tm.tagged_pitch_type.isin(['ChangeUp', 'Changeup'])
    for t in TYPES:
        if t != 'ChangeUp': tm[t] = tm.tagged_pitch_type == t
    tm['minor'] = tm.trackman_game_id.str.contains('Minor|Futures|Test', regex=True)
    tm['is_fb'] = tm.pitch_type_group == 'fastball'
    g = tm.groupby(['pitcher_id', 'season'])
    out = g.size().rename('tm_n').to_frame()
    for m in TM_METRICS:
        out['tm_' + m + '_mean'] = g[m].mean()
        out['tm_' + m + '_std'] = g[m].std()
    for t in TYPES:
        out['tm_mix_' + t] = g[t].mean()
    out['tm_minor_share'] = g['minor'].mean()
    fb = tm[tm.is_fb].groupby(['pitcher_id', 'season'])
    out['tm_fb_speed'] = fb['rel_speed'].mean()
    out['tm_fb_spin'] = fb['spin_rate'].mean()
    out['tm_fb_ivb'] = fb['induced_vert_break'].mean()
    out['tm_fb_hb'] = fb['horz_break'].mean()
    out['tm_fb_relh_std'] = fb['rel_height'].std()
    out['tm_fb_rels_std'] = fb['rel_side'].std()
    out['tm_fb_speed_std'] = fb['rel_speed'].std()
    # release consistency within pitch type (mean of per-type std, weighted)
    pt = tm.groupby(['pitcher_id', 'season', 'pitch_type_group']).agg(n=('rel_height', 'size'), rh=('rel_height', 'std'), rs=('rel_side', 'std')).reset_index()
    pt['rh_w'] = pt.rh * pt.n; pt['rs_w'] = pt.rs * pt.n
    ptg = pt.groupby(['pitcher_id', 'season'])[['rh_w', 'rs_w', 'n']].sum()
    out['tm_rel_consistency_h'] = ptg.rh_w / ptg.n
    out['tm_rel_consistency_s'] = ptg.rs_w / ptg.n
    return out.reset_index()


def prior_weighted(tab, id_col, n_col, metrics, max_season=2026):
    """For each (id, season y): n-weighted mean of metrics over seasons < y, and last active season values."""
    ids = tab[id_col].unique(); seasons = np.arange(tab.season.min(), max_season + 1)
    grid = pd.MultiIndex.from_product([ids, seasons], names=[id_col, 'season'])
    t = tab.set_index([id_col, 'season']).reindex(grid)
    n = t[n_col].fillna(0.0).unstack('season')
    cn = n.cumsum(axis=1).shift(1, axis=1).fillna(0.0)
    act = n.gt(0)
    res = {'prior_n': cn}
    for m in metrics:
        v = t[m].unstack('season')
        wsum = (v.fillna(0.0) * n).cumsum(axis=1).shift(1, axis=1).fillna(0.0)
        nn = (n * v.notna()).cumsum(axis=1).shift(1, axis=1).fillna(0.0)
        res['prior_' + m] = wsum / nn.replace(0, np.nan)
        res['last_' + m] = v.where(act).ffill(axis=1).shift(1, axis=1)
    out = pd.concat({k: v.stack(dropna=False) for k, v in res.items()}, axis=1).reset_index()
    return out
# ===== features2.py =====
"""v2 features: drift/regime-invariant skill priors (deviation from season x game_type league mean),
import warnings; warnings.filterwarnings("ignore")
current-season deviations, and explicit level reference for offset modeling.
Built on top of features.build_features (v1)."""
import os


SKILL_P = ['n', 'res', 'n_R', 'res_R', 'n_F', 'res_F', 'n_L', 'res_L', 'rev_res', 'mid_res', 'far_res',
           'n_ahead', 'res_ahead', 'n_behind', 'res_behind', 'n_2k', 'res_2k', 'n_3b', 'res_3b', 'n_home', 'res_home']
SKILL_B = ['n', 'res', 'mid_res', 'n_vsL', 'res_vsL', 'n_2k', 'res_2k']


def league_table(tr):
    """season x game_type mean success + failure-mode means (from training rows)."""
    L = tr.groupby(['season', 'game_type']).control_success.mean().unstack()
    La = tr.groupby('season').control_success.mean()
    return {'L_gt': L, 'L_all': La}


def build_stats(train):
    st = build_stats_v1(train)
    tr = train.reset_index(drop=True)
    lt = league_table(tr)
    st.update(lt)
    # residuals vs season x game_type mean
    Lrow = tr.set_index(['season', 'game_type']).index.map(lambda k: lt['L_gt'].loc[k[0], k[1]]).values
    y = tr.control_success.values.astype(float)
    res = y - Lrow
    pind = _recover_indicators(tr, 'pitcher_id', 'asof_pitcher_n', RATE_COLS_P)
    bind = _recover_indicators(tr, 'batter_id', 'asof_batter_n', RATE_COLS_B)
    # failure-mode residuals vs season x game_type means
    fm = pd.DataFrame({'season': tr.season, 'game_type': tr.game_type, 'rev': pind['rev'].values,
                       'mid': pind['mid'].values})
    fm['far'] = 1 - y - fm.rev - fm.mid
    fm['far'] = fm['far'].clip(0, 1)
    fmm = fm.groupby(['season', 'game_type'])[['rev', 'mid', 'far']].transform('mean')
    st['FM_gt'] = fm.groupby(['season', 'game_type'])[['rev', 'mid', 'far']].mean()
    isF = (tr.game_type == 'F').values
    ahead = (tr.strikes_before > tr.balls_before).values
    behind = (tr.balls_before > tr.strikes_before).values
    two_k = (tr.strikes_before == 2).values
    three_b = (tr.balls_before == 3).values
    vsL = (tr.batter_hand == 1).values
    home = (tr.top_bottom == 'T').values
    p = pd.DataFrame({'pitcher_id': tr.pitcher_id, 'season': tr.season, 'n': 1.0, 'res': res,
                      'n_R': (~isF) * 1.0, 'res_R': (~isF) * res, 'n_F': isF * 1.0, 'res_F': isF * res,
                      'n_L': vsL * 1.0, 'res_L': vsL * res,
                      'rev_res': fm.rev.values - fmm.rev.values, 'mid_res': fm.mid.values - fmm.mid.values,
                      'far_res': fm.far.values - fmm.far.values,
                      'n_ahead': ahead * 1.0, 'res_ahead': ahead * res, 'n_behind': behind * 1.0, 'res_behind': behind * res,
                      'n_2k': two_k * 1.0, 'res_2k': two_k * res, 'n_3b': three_b * 1.0, 'res_3b': three_b * res,
                      'n_home': home * 1.0, 'res_home': home * res})
    st['ps2'] = p.groupby(['pitcher_id', 'season']).sum().reset_index()
    bmid = bind['mid'].values
    bmm = pd.DataFrame({'season': tr.season, 'game_type': tr.game_type, 'mid': bmid}).groupby(['season', 'game_type']).mid.transform('mean').values
    vsLHP = (tr.pitcher_hand == 1).values
    b = pd.DataFrame({'batter_id': tr.batter_id, 'season': tr.season, 'n': 1.0, 'res': res, 'mid_res': bmid - bmm,
                      'n_vsL': vsLHP * 1.0, 'res_vsL': vsLHP * res, 'n_2k': two_k * 1.0, 'res_2k': two_k * res})
    st['bs2'] = b.groupby(['batter_id', 'season']).sum().reset_index()
    # team x season levels (regime proxies): pitcher_team and batter_team deviations
    st['team_p'] = tr.groupby(['season', 'pitcher_team_id']).control_success.mean()
    st['team_b'] = tr.groupby(['season', 'batter_team_id']).control_success.mean()
    # ---- pitcher role stats per season (games, starts, pitches/game) from row-order game segmentation ----
    tA = np.where(tr.top_bottom == 'T', tr.pitcher_team_id, tr.batter_team_id)
    tB = np.where(tr.top_bottom == 'T', tr.batter_team_id, tr.pitcher_team_id)
    gk = pd.Series(tr.season.astype(str) + '_' + tr.game_month.astype(str) + '_' + tr.game_dayofweek.astype(str) + '_' + pd.Series(tA).astype(str) + '_' + pd.Series(tB).astype(str) + '_' + tr.game_type)
    gid = ((gk != gk.shift()) | (tr.inning < tr.inning.shift())).cumsum().values
    g = pd.DataFrame({'pitcher_id': tr.pitcher_id, 'season': tr.season, 'gid': gid, 'inning': tr.inning, 'tb': tr.top_bottom})
    first = g.groupby(['gid', 'tb']).pitcher_id.first().rename('starter').reset_index()
    g = g.merge(first, on=['gid', 'tb'], how='left')
    g['is_start'] = (g.pitcher_id == g.starter)
    pg = g.groupby(['pitcher_id', 'season', 'gid']).agg(n=('inning', 'size'), start=('is_start', 'max'), inn_first=('inning', 'min'), inn_last=('inning', 'max')).reset_index()
    role = pg.groupby(['pitcher_id', 'season']).agg(games=('n', 'size'), starts=('start', 'mean'), ppg=('n', 'mean'), inn_first=('inn_first', 'mean'), inn_last=('inn_last', 'mean')).reset_index()
    st['role'] = role
    # end-of-season form: last 5 games and second half of the pitcher's season (per pitcher, season)
    pg2 = g.groupby(['pitcher_id', 'season', 'gid']).agg(n=('inning', 'size')).reset_index()
    pg2['s'] = pd.DataFrame({'pitcher_id': tr.pitcher_id, 'season': tr.season, 'gid': gid, 'y': tr.control_success}).groupby(['pitcher_id', 'season', 'gid']).y.sum().values
    pg2['gord'] = pg2.groupby(['pitcher_id', 'season']).cumcount(ascending=False)  # 0 = last game
    last5 = pg2[pg2.gord < 5].groupby(['pitcher_id', 'season']).agg(n_last5g=('n', 'sum'), s_last5g=('s', 'sum')).reset_index()
    h = pd.DataFrame({'pitcher_id': tr.pitcher_id, 'season': tr.season, 'y': tr.control_success.astype(float)})
    h['k'] = h.groupby(['pitcher_id', 'season']).cumcount(); h['tot'] = h.groupby(['pitcher_id', 'season']).y.transform('size')
    h2 = h[h.k >= h.tot / 2].groupby(['pitcher_id', 'season']).agg(n_h2=('y', 'size'), s_h2=('y', 'sum')).reset_index()
    st['endform'] = last5.merge(h2, on=['pitcher_id', 'season'], how='outer').fillna(0.0)
    try:
        st['tm'] = build_tm_table()
    except Exception as e:
        print('trackman table unavailable:', e)
        st['tm'] = None
    return st


def level_ref(df, stats, mode='prev', guess=None):
    """Reference success level per row (used for offset / cur deviation).
    mode='true': own season x game_type mean (training rows only).
    mode='prev': previous season's mean for that game_type (persistence forecast); 2019 -> own.
    For rows whose season is not in stats (test), use `guess` dict {'R': p, 'F': p} or last season + 0."""
    L = stats['L_gt']
    seasons = df.season.values; gt = df.game_type.values
    out = np.full(len(df), np.nan)
    max_s = L.index.max()
    for g in ('R', 'F'):
        m = gt == g
        if mode == 'true':
            ref = pd.Series(seasons[m]).map(L[g]).values
        else:
            ref = pd.Series(seasons[m] - 1).map(L[g]).values
            first = seasons[m] == L.index.min()
            ref = np.where(first, pd.Series(seasons[m]).map(L[g]).values, ref)
        # unseen seasons (test): guess or last available
        unseen = seasons[m] > max_s
        gval = (guess or {}).get(g, L[g].loc[max_s])
        ref = np.where(unseen, gval, ref)
        out[m] = ref
    return out


def build_features(df, stats, mode='prev', guess=None):
    F = build_features_v1(df, stats)
    F = add_matchup_features(F, df.reset_index(drop=True), stats)
    d = df.reset_index(drop=True)
    pp = _prior_table(stats['ps2'], 'pitcher_id', SKILL_P, last_col='res')
    bp = _prior_table(stats['bs2'], 'batter_id', SKILL_B, last_col='res')
    pp = pp.rename(columns={c: 'P_' + c for c in pp.columns if c not in ('pitcher_id', 'season')})
    bp = bp.rename(columns={c: 'B_' + c for c in bp.columns if c not in ('batter_id', 'season')})
    d = d.merge(pp, on=['pitcher_id', 'season'], how='left').merge(bp, on=['batter_id', 'season'], how='left')
    for c in d.columns:
        if c.startswith(('P_prior_', 'B_prior_')):
            d[c] = d[c].fillna(0.0)

    def rate(num, den, minn=1):
        den = den.values if hasattr(den, 'values') else den
        num = num.values if hasattr(num, 'values') else num
        with np.errstate(invalid='ignore', divide='ignore'):
            return np.where(den >= minn, num / np.maximum(den, 1e-9), np.nan)

    def shrink(num, den, k):
        return num / (den + k)
    # ---- pitcher skill (deviation) priors ----
    F['P_skill'] = rate(d.P_prior_res, d.P_prior_n)
    for k in (200, 1000):
        F[f'P_skill_shr{k}'] = shrink(d.P_prior_res, d.P_prior_n, k)
    F['P_skill_R'] = rate(d.P_prior_res_R, d.P_prior_n_R)
    F['P_skill_F'] = rate(d.P_prior_res_F, d.P_prior_n_F)
    F['P_skill_gt'] = np.where(d.game_type == 'F', F['P_skill_F'], F['P_skill_R'])
    F['P_skill_gt_shr300'] = np.where(d.game_type == 'F', shrink(d.P_prior_res_F, d.P_prior_n_F, 300), shrink(d.P_prior_res_R, d.P_prior_n_R, 300))
    F['P_skill_vsL'] = rate(d.P_prior_res_L, d.P_prior_n_L)
    F['P_skill_vsR'] = rate(d.P_prior_res - d.P_prior_res_L, d.P_prior_n - d.P_prior_n_L)
    F['P_skill_vsHand'] = np.where(d.batter_hand == 1, F['P_skill_vsL'], F['P_skill_vsR'])
    F['P_skill_vsHand_shr300'] = np.where(d.batter_hand == 1, shrink(d.P_prior_res_L, d.P_prior_n_L, 300),
                                          shrink(d.P_prior_res - d.P_prior_res_L, d.P_prior_n - d.P_prior_n_L, 300))
    F['P_rev_skill'] = rate(d.P_prior_rev_res, d.P_prior_n)
    F['P_mid_skill'] = rate(d.P_prior_mid_res, d.P_prior_n)
    F['P_far_skill'] = rate(d.P_prior_far_res, d.P_prior_n)
    F['P_skill_ahead'] = rate(d.P_prior_res_ahead, d.P_prior_n_ahead, 30)
    F['P_skill_behind'] = rate(d.P_prior_res_behind, d.P_prior_n_behind, 30)
    F['P_skill_2k'] = rate(d.P_prior_res_2k, d.P_prior_n_2k, 30)
    F['P_skill_3b'] = rate(d.P_prior_res_3b, d.P_prior_n_3b, 30)
    F['P_skill_home'] = rate(d.P_prior_res_home, d.P_prior_n_home, 30)
    F['P_skill_away'] = rate(d.P_prior_res - d.P_prior_res_home, d.P_prior_n - d.P_prior_n_home, 30)
    F['P_skill_ha'] = np.where(d.top_bottom == 'T', F['P_skill_home'], F['P_skill_away'])
    # count-context skill matching the row's count
    ah = (d.strikes_before > d.balls_before).values; bh = (d.balls_before > d.strikes_before).values
    F['P_skill_count'] = np.where(ah, F['P_skill_ahead'], np.where(bh, F['P_skill_behind'], np.nan))
    F['P_last_skill'] = rate(d.P_last_s, d.P_last_n) if 'P_last_s' in d else np.nan  # (last_s here is res of last season)
    # ---- batter skill priors ----
    F['B_skill'] = rate(d.B_prior_res, d.B_prior_n)
    F['B_skill_shr300'] = shrink(d.B_prior_res, d.B_prior_n, 300)
    F['B_mid_skill'] = rate(d.B_prior_mid_res, d.B_prior_n)
    F['B_skill_vsL'] = rate(d.B_prior_res_vsL, d.B_prior_n_vsL, 30)
    F['B_skill_vsR'] = rate(d.B_prior_res - d.B_prior_res_vsL, d.B_prior_n - d.B_prior_n_vsL, 30)
    F['B_skill_vsHand'] = np.where(d.pitcher_hand == 1, F['B_skill_vsL'], F['B_skill_vsR'])
    F['B_skill_2k'] = rate(d.B_prior_res_2k, d.B_prior_n_2k, 30)
    F['B_last_skill'] = rate(d.B_last_s, d.B_last_n) if 'B_last_s' in d else np.nan
    # ---- level reference & current-season deviations ----
    Lref = level_ref(d, stats, mode=mode, guess=guess)
    F['L_ref'] = Lref
    # all-game level reference for cur (cur mixes R and F): use overall season mean analogously
    La = stats['L_all']; max_s = La.index.max()
    if mode == 'true':
        La_row = pd.Series(d.season.values).map(La).values
    else:
        La_row = pd.Series(d.season.values - 1).map(La).values
        La_row = np.where(d.season.values == La.index.min(), pd.Series(d.season.values).map(La).values, La_row)
    ga = None if guess is None else guess.get('all', None)
    La_row = np.where(d.season.values > max_s, (La.loc[max_s] if ga is None else ga), La_row)
    F['L_all_ref'] = La_row
    F['p_cur_dev'] = F['p_cur_s_rate'] - La_row
    F['b_cur_dev'] = F['b_cur_s_rate'] - La_row
    F['p_cur_dev_shr200'] = (np.nan_to_num(F['p_cur_s'].values - F['p_cur_n'].values * La_row) + 200 * np.nan_to_num(F['P_skill'].values)) / (F['p_cur_n'].values + 200)
    bcs = np.nan_to_num(F['b_cur_s_rate'].values - La_row) * F['b_cur_n'].values
    F['b_cur_dev_shr300'] = (bcs + 300 * np.nan_to_num(F['B_skill'].values)) / (F['b_cur_n'].values + 300)
    F['p_cur_minus_skill'] = F['p_cur_dev'] - F['P_skill']
    F['b_cur_minus_skill'] = F['b_cur_dev'] - F['B_skill']
    # combined best-guess pitcher rate = Lref + shrunk skill
    F['p_est'] = Lref + F['p_cur_dev_shr200']
    F['b_est'] = Lref + F['b_cur_dev_shr300']
    F['home_team'] = np.where(d.top_bottom == 'T', d.pitcher_team_id, d.batter_team_id)
    if os.environ.get('LG_FEATS', '1') == '1':  # default ON (adopted 08-27): label-source regime of LG-involved games
        F['LG_game'] = ((d.pitcher_team_id.values == 13) | (d.batter_team_id.values == 13)).astype(float)
        if os.environ.get('LG_MAY', '1') == '1':  # default ON (adopted 08-27): regime switched in May 2023; F rows are new-regime from 2023 start
            F['LG_regime'] = F['LG_game'].values * ((d.season.values > 2023) | ((d.season.values == 2023) & ((d.game_month.values >= 5) | (d.game_type.values == 'F'))))
        else:
            F['LG_regime'] = F['LG_game'].values * (d.season.values >= 2023)
    if os.environ.get('LG30F') == '1':  # explicit LG-process 3-0 count indicator (row's own count + team ids)
        F['LG_30'] = F['LG_regime'].values * ((d.balls_before.values == 3) & (d.strikes_before.values == 0)) * (d.game_type.values == 'R')
    if os.environ.get('TEAM_LAST') == '1' and 'team_p' in stats:
        # last-season team effects (deviation from league-season mean), pitching team and home team; test season -> last training season
        tp = stats['team_p'].reset_index(); tp.columns = ['season', 'team', 'rate']
        lg = stats['league'].set_index('season')['league_rate'] if 'league' in stats else tp.groupby('season').rate.mean()
        tp['dev'] = tp.rate.values - tp.season.map(lg).values
        mx = int(tp.season.max()); dev_map = {(int(r.season), int(r.team)): r.dev for r in tp.itertuples()}
        prev_season = np.minimum(d.season.values - 1, mx)
        F['TEAM_last_dev_p'] = np.array([dev_map.get((int(s_), int(t)), 0.0) for s_, t in zip(prev_season, d.pitcher_team_id.values)])
        F['TEAM_last_dev_home'] = np.array([dev_map.get((int(s_), int(t)), 0.0) for s_, t in zip(prev_season, F['home_team'].values)])
    # ---- role priors ----
    role = stats.get('role')
    if role is not None:
        rp = prior_weighted(role, 'pitcher_id', 'games', ['starts', 'ppg', 'inn_first', 'inn_last'])
        rp = rp.rename(columns={c: 'ROLE_' + c for c in rp.columns if c not in ('pitcher_id', 'season')})
        d = d.merge(rp, on=['pitcher_id', 'season'], how='left')
        F['ROLE_games_prior'] = d.ROLE_prior_n.fillna(0.0)
        F['ROLE_start_share'] = d.ROLE_prior_starts  # weighted mean of per-season start count?? -> use share
        F['ROLE_ppg'] = d.ROLE_prior_ppg
        F['ROLE_ppg_last'] = d.ROLE_last_ppg
        F['ROLE_inn_first'] = d.ROLE_prior_inn_first
        F['ROLE_inn_last'] = d.ROLE_prior_inn_last
        F['ROLE_cur_pace'] = F['p_cur_n'] / np.maximum(d.game_month.values - 2, 1)
        F['ROLE_inning_minus_first'] = d.inning.values - F['ROLE_inn_first']
    # ---- trackman priors ----
    tm = stats.get('tm')
    if tm is not None:
        mets = [c for c in tm.columns if c.startswith('tm_') and c != 'tm_n']
        tp = prior_weighted(tm, 'pitcher_id', 'tm_n', mets)
        tp = tp.rename(columns={c: 'TM_' + c for c in tp.columns if c not in ('pitcher_id', 'season')})
        d = d.merge(tp, on=['pitcher_id', 'season'], how='left')
        F['TM_n_prior'] = d.TM_prior_n.fillna(0.0)
        for m in mets:
            F['TM_' + m[3:]] = d['TM_prior_' + m]
        for m in ['tm_fb_speed', 'tm_rel_speed_mean', 'tm_spin_rate_mean', 'tm_fb_relh_std', 'tm_fb_rels_std', 'tm_rel_consistency_h', 'tm_rel_consistency_s', 'tm_minor_share']:
            F['TM_last_' + m[3:]] = d['TM_last_' + m]
        F['TM_fb_speed_trend'] = d['TM_last_tm_fb_speed'] - d['TM_prior_tm_fb_speed']
    F['p_cur_logn'] = np.log1p(F['p_cur_n']); F['b_cur_logn'] = np.log1p(F['b_cur_n'])
    F['p_prior_logn'] = np.log1p(F['p_prior_n']); F['b_prior_logn'] = np.log1p(F['b_prior_n'])
    return F


SKILL_FEATS = ['P_skill', 'P_skill_shr200', 'P_skill_shr1000', 'P_skill_R', 'P_skill_F', 'P_skill_gt', 'P_skill_gt_shr300',
               'P_skill_vsL', 'P_skill_vsR', 'P_skill_vsHand', 'P_skill_vsHand_shr300', 'P_rev_skill', 'P_mid_skill',
               'P_far_skill', 'P_skill_ahead', 'P_skill_behind', 'P_skill_2k', 'P_skill_3b', 'P_skill_home', 'P_skill_away',
               'P_skill_ha', 'P_skill_count', 'B_skill', 'B_skill_shr300', 'B_mid_skill', 'B_skill_vsL', 'B_skill_vsR',
               'B_skill_vsHand', 'B_skill_2k', 'L_ref', 'L_all_ref', 'p_cur_dev', 'b_cur_dev', 'p_cur_dev_shr200',
               'b_cur_dev_shr300', 'p_cur_minus_skill', 'b_cur_minus_skill', 'p_est', 'b_est', 'home_team',
               'p_cur_logn', 'b_cur_logn', 'p_prior_logn', 'b_prior_logn']
# ===== bayes_level.py =====
"""Explicit dynamic-Bayesian estimator of each pitcher's current-season control level (probability scale, normal approx).
State: deviation d_{p,s} = theta_{p,s} - mu_s. Transition: d_s = a * d_{s-1} + eps, eps ~ N(0, tau2) (per gap year).
Observation within season: successes ~ Binomial(n, mu_s + d) -> normal approx with per-pitch variance sig2.
Per-row posterior uses ONLY the row's own season-to-date (n, s) and the pitcher's prior-season totals (training stats)."""

SIG2 = 0.25


def season_priors(ps, league, a, tau2, v_new, max_season=2026):
    """Per (pitcher, season y): prior mean/var of the deviation BEFORE observing season y, from recursion over prior seasons."""
    seasons = np.arange(int(ps.season.min()), max_season + 1)
    pit = np.sort(ps.pitcher_id.unique())
    n_w = ps.pivot(index='pitcher_id', columns='season', values='n').reindex(index=pit, columns=seasons).fillna(0.0).values
    s_w = ps.pivot(index='pitcher_id', columns='season', values='s').reindex(index=pit, columns=seasons).fillna(0.0).values
    mu = np.array([league.get(int(y), np.nan) for y in seasons])
    # league mean for seasons beyond training: persistence of the last known
    last_mu = mu[~np.isnan(mu)][-1]; mu = np.where(np.isnan(mu), last_mu, mu)
    m = np.zeros(len(pit)); v = np.full(len(pit), v_new); started = np.zeros(len(pit), bool)
    prior_m = np.zeros_like(n_w); prior_v = np.zeros_like(n_w)
    for j, y in enumerate(seasons):
        prior_m[:, j] = m; prior_v[:, j] = v
        n = n_w[:, j]; s = s_w[:, j]; obs = n > 0
        # update with this season's totals (posterior at end of season)
        prec = 1.0 / v + np.where(obs, n / SIG2, 0.0)
        mean_obs = np.where(obs, (s - n * mu[j]) / np.maximum(n, 1), 0.0)
        m_post = (m / v + np.where(obs, mean_obs * n / SIG2, 0.0)) / prec; v_post = 1.0 / prec
        started |= obs
        # transition to next season (only for pitchers that have started; others keep the v_new prior)
        m = np.where(started, a * m_post, 0.0); v = np.where(started, a * a * v_post + tau2, v_new)
    tab = pd.DataFrame({'pitcher_id': np.repeat(pit, len(seasons)), 'season': np.tile(seasons, len(pit)),
                        'prior_m': prior_m.ravel(), 'prior_v': prior_v.ravel()})
    return tab, dict(zip(seasons.tolist(), mu.tolist()))


def row_posterior(df, F, tab, mu_by_season, v_new):
    d = df[['pitcher_id', 'season']].reset_index(drop=True).merge(tab, on=['pitcher_id', 'season'], how='left')
    m0 = d.prior_m.fillna(0.0).values; v0 = d.prior_v.fillna(v_new).values
    mu = pd.Series(df.season.values).map(mu_by_season).values
    n = np.maximum(F['p_cur_n'].values, 0.0); s = np.clip(np.nan_to_num(F['p_cur_s'].values), 0.0, np.maximum(n, 0.0))  # guard: s in [0, n]
    prec = 1.0 / v0 + n / SIG2
    m1 = (m0 / v0 + (s - n * mu) / SIG2) / prec; v1 = 1.0 / prec
    return mu + m1, v1, m0, v0



# ===== features_dev.py =====
"""Season-invariant 'deviation view': subtract the training-season league mean of each rate-type feature.
For rows of seasons beyond training (val/test), the last training season's mean is used (persistence)."""

BAYES_HP = dict(a=0.6, tau2=0.004, v_new=0.004)

SUCCESS_RATE_FEATS = ['p_cur_s_rate', 'p_prior_s_rate', 'p_last_rate', 'asof_p_success_rate', 'p_cur_s_shr100', 'p_cur_s_shr500',
                      'p_all_s_shr200', 'b_cur_s_rate', 'b_prior_s_rate', 'b_last_rate', 'asof_b_success_rate', 'b_cur_s_shr300',
                      'b_all_s_shr300', 'asof_p_prev1_game_success_rate', 'asof_p_prev3_game_success_rate', 'asof_p_prev5_game_success_rate',
                      'p_mix_exp_rate', 'p_prior_srate_fb', 'p_prior_srate_br', 'p_prior_srate_os', 'pb_prior_rate', 'pb_prior_shr30',
                      'p_prior_F_rate', 'p_prior_R_rate', 'p_prior_F23_rate', 'p_prior_vsL_rate', 'p_prior_vsR_rate', 'p_prior_vsHand_rate']
MODE_RATE_FEATS = {'rev': ['p_cur_rev_rate', 'p_prior_rev_rate', 'asof_p_reverse_rate'],
                   'mid': ['p_cur_mid_rate', 'p_prior_mid_rate', 'asof_p_middle_rate', 'b_cur_mid_rate', 'b_prior_mid_rate', 'asof_b_middle_rate',
                           'asof_p_prev1_game_middle_rate', 'asof_p_prev3_game_middle_rate', 'asof_p_prev5_game_middle_rate'],
                   'ball': ['p_cur_ball_rate', 'p_prior_ball_rate', 'asof_p_ball_rate'],
                   'strike': ['p_cur_strike_rate', 'p_prior_strike_rate', 'asof_p_strike_rate']}


def season_means(train, ind):
    """Per-season league means of success and failure-mode/ball/strike rates from training rows."""
    d = pd.DataFrame({'season': train.season.values, 's': train.control_success.values.astype(float), 'rev': ind['rev'].values,
                      'mid': ind['mid'].values, 'ball': ind['ball'].values, 'strike': ind['strike'].values})
    return d.groupby('season').mean()


def deviation_view(F, seasons, means, bayes=None):
    """Return a copy of F with rate features replaced by deviations from the season mean (+ optional bayes features)."""
    F = F.copy(); seasons = np.asarray(seasons)
    max_s = means.index.max()
    key = np.minimum(seasons, max_s)
    for col in SUCCESS_RATE_FEATS:
        if col in F: F[col] = F[col].values - means['s'].reindex(key).values
    for mode, cols in MODE_RATE_FEATS.items():
        for col in cols:
            if col in F: F[col] = F[col].values - means[mode].reindex(key).values
    if bayes is not None:
        for k, v in bayes.items(): F[k] = v
    return F


def bayes_features(df, F, stats, a=0.6, tau2=0.004, v_new=0.004, src=False):
    ps = stats['ps'][['pitcher_id', 'season', 'n', 's'] + (['n_LG', 's_LG', 'n_F', 's_F'] if src else [])].copy()
    league = dict(zip(stats['league'].season, stats['league'].league_rate))
    if src:
        # remove label-source effects from pitcher-season successes so the state-space level is source-free
        eff = stats['src_eff']; mx = int(eff.index.max())
        def _e(col, seasons): return eff[col].reindex(np.minimum(np.asarray(seasons, dtype=int), mx)).values
        nB = ps.n.values - ps.n_LG.values - ps.n_F.values
        ps['s'] = ps.s.values - ps.n_LG.values * _e('eff_LG', ps.season) - ps.n_F.values * _e('eff_F', ps.season) - nB * _e('eff_B', ps.season)
    tab, mu = season_priors(ps[['pitcher_id', 'season', 'n', 's']], league, a, tau2, v_new)
    if not src:
        pm, pv, m0, v0 = row_posterior(df, F, tab, mu, v_new)
        mu_row = pd.Series(np.asarray(df.season)).map(mu).values
        return {'bayes_dev': pm - mu_row, 'bayes_pv': pv, 'bayes_m0': m0, 'bayes_v0': v0}
    # season-to-date successes: subtract the pitcher's expected source effect (typical source mix), then add the row's source effect back
    seas = np.asarray(df.season); is_lgp = (np.asarray(df.pitcher_team_id) == 13)
    fsh = np.nan_to_num(F['p_prior_F_share'].values, nan=0.0) if 'p_prior_F_share' in F else np.zeros(len(df))
    share_F = np.clip(fsh, 0.0, 1.0); share_LG = np.where(is_lgp, 1.0 - share_F, 0.11 * (1.0 - share_F)); share_B = np.clip(1.0 - share_LG - share_F, 0.0, 1.0)
    e_LG, e_F, e_B = _e('eff_LG', seas), _e('eff_F', seas), _e('eff_B', seas)
    exp_eff = share_LG * e_LG + share_F * e_F + share_B * e_B
    F2 = F[['p_cur_n', 'p_cur_s']].copy(); F2['p_cur_s'] = F2['p_cur_s'].values - np.maximum(F2['p_cur_n'].values, 0.0) * exp_eff
    pm, pv, m0, v0 = row_posterior(df, F2, tab, mu, v_new)
    row_src = np.where(np.asarray(df.game_type) == 'F', e_F, np.where(is_lgp | (np.asarray(df.batter_team_id) == 13), e_LG, e_B))
    mu_row = pd.Series(seas).map(mu).values
    return {'bayes_dev': pm - mu_row + row_src, 'bayes_pv': pv, 'bayes_m0': m0, 'bayes_v0': v0}


def batter_bayes_features(df, F, stats, a=0.6, tau2=0.001, v_new=0.0015):
    """Dynamic-Bayesian posterior of the BATTER's current-season deviation (same machinery as pitchers, bs table)."""
    bs = stats['bs'][['batter_id', 'season', 'n', 's']].rename(columns={'batter_id': 'pitcher_id'})
    league = dict(zip(stats['league'].season, stats['league'].league_rate))
    tab, mu = season_priors(bs, league, a, tau2, v_new)
    d = df[['batter_id', 'season']].reset_index(drop=True).rename(columns={'batter_id': 'pitcher_id'}).merge(tab, on=['pitcher_id', 'season'], how='left')
    m0 = d.prior_m.fillna(0.0).values; v0 = d.prior_v.fillna(v_new).values
    mu_row = pd.Series(np.asarray(df.season)).map(mu).values
    n = F['b_cur_n'].values; s = np.nan_to_num(F['b_cur_s_rate'].values * n)
    prec = 1.0 / v0 + n / 0.25
    m1 = (m0 / v0 + (s - n * mu_row) / 0.25) / prec; v1 = 1.0 / prec
    return {'bbayes_dev': m1, 'bbayes_pv': v1, 'bbayes_m0': m0, 'bbayes_v0': v0}
# ===== nn_core.py =====
"""NN core shared by training (nn.py) and inference (script.py)."""

CAT_SPECS = {'pitcher_id': 64, 'batter_id': 32, 'pitcher_team': 4, 'batter_team': 4, 'home_team': 4, 'count_state': 4, 'base_state': 3}


def build_net(n_num, cat_sizes, hidden=(512, 256, 128), drop=0.2):
    import torch, torch.nn as nn

    class Net(nn.Module):
        def __init__(self):
            super().__init__()
            self.embs = nn.ModuleList([nn.Embedding(n + 1, d) for n, d in cat_sizes])
            d_in = n_num + sum(d for _, d in cat_sizes)
            layers = []
            for h in hidden:
                layers += [nn.Linear(d_in, h), nn.BatchNorm1d(h), nn.SiLU(), nn.Dropout(drop)]; d_in = h
            self.mlp = nn.Sequential(*layers)
            self.head4 = nn.Linear(d_in, 4); self.head_bs = nn.Linear(d_in, 3); self.head_pt = nn.Linear(d_in, 3)

        def forward(self, xn, xc):
            e = [emb(xc[:, i]) for i, emb in enumerate(self.embs)]
            h = self.mlp(torch.cat([xn] + e, 1))
            return self.head4(h), self.head_bs(h), self.head_pt(h)
    return Net()


def transform_numeric(F, num_feats, qt, nan_cols):
    X = F[num_feats].astype(np.float32).values
    nanmask = np.isnan(X)
    Xq = qt.transform(np.nan_to_num(X, nan=0.0)).astype(np.float32)
    Xq[nanmask] = 0.0
    return np.concatenate([Xq, nanmask[:, nan_cols].astype(np.float32)], 1)


def transform_cats(F, cats, maps):
    codes = np.zeros((len(F), len(cats)), dtype=np.int64)
    for i, c in enumerate(cats):
        codes[:, i] = pd.Series(F[c].values).map(maps[c]).fillna(0).astype(int).values
    return codes


def nn_predict(models, Xn, Xc, bs=32768, init4=None):
    import torch
    out = np.zeros(len(Xn))
    Xn_t = torch.tensor(Xn); Xc_t = torch.tensor(Xc); I4 = None if init4 is None else torch.tensor(np.asarray(init4, dtype=np.float32))
    for net in models:
        net.eval(); ps = []
        with torch.no_grad():
            for i in range(0, len(Xn), bs):
                o4, _, _ = net(Xn_t[i:i + bs], Xc_t[i:i + bs])
                if I4 is not None: o4 = o4 + I4[i:i + bs]
                ps.append(torch.softmax(o4, 1)[:, 0].numpy())
        out += np.concatenate(ps)
    return out / len(models)
# ===== inference =====
ID_COL, TARGET_COL = 'row_id', 'control_success'


def bayes_init(df, F, stats, meta):
    """Row-wise dynamic-Bayesian pitcher level (uses the row's own season-to-date record + training-season totals)."""
    off = str(meta.get('offset', ''))
    bay = bayes_features(df, F, stats, src=off.endswith('_src'), **BAYES_HP)
    mu = dict(zip(stats['league'].season, stats['league'].league_rate)); mx = max(mu)
    mu_row = pd.Series(np.asarray(df.season)).map(mu).fillna(mu[mx]).values
    pm = np.clip(mu_row + bay['bayes_dev'] + ((F['CTX_hand_adj'].values + F['CTX_2k_adj'].values) if off.startswith('bayes_ctx') else 0.0), 0.05, 0.95)
    if meta.get('type') in ('lgb_mc', 'cat_mc'):
        fs = meta['fshare']
        return np.stack([np.log(pm)] + [np.log((1 - pm) * fs[k]) for k in range(3)], 1)
    return logit(pm)


def main():
    TEST_DIR, MODEL_DIR, OUT_DIR = './data', './model', './output'
    test = pd.read_csv(os.path.join(TEST_DIR, 'test.csv'), encoding='utf-8-sig', dtype={'base_state': str, 'top_bottom': str, 'game_type': str, 'row_id': str})  # keep code columns as strings regardless of file size
    sub = pd.read_csv(os.path.join(TEST_DIR, 'sample_submission.csv'), encoding='utf-8-sig')
    print('test', test.shape, 'sub', sub.shape, flush=True)
    stats = joblib.load(os.path.join(MODEL_DIR, 'stats.pkl'))
    ens = json.load(open(os.path.join(MODEL_DIR, 'ensemble.json')))
    preds = []
    weights = []
    feat_cache = {}
    for mfile in ens['models']:
        meta = json.load(open(os.path.join(MODEL_DIR, mfile)))
        mode = meta.get('mode', 'prev'); guess = meta.get('level_guess')
        key = (mode, json.dumps(guess, sort_keys=True))
        if key not in feat_cache:
            # Row-wise features: each row uses only its own columns + training-data statistics.
            F = add_change_features(build_features(test, stats, mode=mode, guess=guess))
            feat_cache[key] = F
        F = feat_cache[key]
        if meta.get('type') == 'nn':
            import torch
            prep = joblib.load(os.path.join(MODEL_DIR, meta['prep']))
            Fn = F.copy(); Fn['season_rel'] = np.clip(prep['max_season'] - Fn['season'].values, 0, 10)
            Xn = transform_numeric(Fn, prep['num_feats'], prep['qt'], prep['nan_cols'])
            Xc = transform_cats(Fn, prep['cats'], prep['maps'])
            nets = []
            for b in meta['boosters']:
                net = build_net(Xn.shape[1], prep['sizes'], tuple(prep['hidden']), prep['drop'])
                net.load_state_dict(torch.load(os.path.join(MODEL_DIR, b), map_location='cpu')); nets.append(net)
            init4 = bayes_init(test, F, stats, {**meta, 'type': 'lgb_mc'}) if str(meta.get('offset', '')).startswith('bayes') else None
            pn = nn_predict(nets, Xn, Xc, init4=init4)
            raw = logit(np.clip(pn, 1e-6, 1 - 1e-6)) + float(meta.get('logit_shift', 0.0))
            preds.append(expit(raw)); weights.append(float(meta.get('weight', 1.0)))
            print('model', mfile, 'pred mean', round(float(preds[-1].mean()), 4), flush=True)
            continue
        X = F[meta['feats']]
        raw = np.zeros(len(X))
        init = None
        if str(meta.get('offset', '')).startswith('bayes'):
            init = bayes_init(test, F, stats, meta)
        if meta.get('type') in ('cat', 'cat_mc'):
            from catboost import CatBoostClassifier
            Xc = X.copy()
            for c in meta['cat']: Xc[c] = Xc[c].astype(int)
            for b in meta['boosters']:
                m = CatBoostClassifier(); m.load_model(os.path.join(MODEL_DIR, b))
                if init is not None:
                    from catboost import Pool
                    rw = m.predict(Pool(Xc, cat_features=meta['cat'], baseline=init), prediction_type='RawFormulaVal')
                    pr = softmax(rw, axis=1)[:, 0] if meta.get('type') == 'cat_mc' else expit(rw)
                else:
                    pr = m.predict_proba(Xc); pr = pr[:, 0] if meta.get('type') == 'cat_mc' else pr[:, 1]
                raw += logit(np.clip(pr, 1e-6, 1 - 1e-6))
            raw /= len(meta['boosters']); raw += float(meta.get('logit_shift', 0.0))
            preds.append(expit(raw)); weights.append(float(meta.get('weight', 1.0)))
            print('model', mfile, 'pred mean', round(float(preds[-1].mean()), 4), flush=True)
            continue
        for b in meta['boosters']:
            m = lgb.Booster(model_file=os.path.join(MODEL_DIR, b))
            if meta.get('type') == 'lgb_mc':
                if init is not None:
                    pr = softmax(m.predict(X, raw_score=True) + init, axis=1)[:, 0]
                else:
                    pr = m.predict(X)[:, 0]
                raw += logit(np.clip(pr, 1e-6, 1 - 1e-6))
            else:
                raw += m.predict(X, raw_score=True) + (0.0 if init is None else init)
        raw /= len(meta['boosters'])
        if meta.get('offset'):
            raw += logit(F['L_ref'].values)
        raw += float(meta.get('logit_shift', 0.0))
        preds.append(expit(raw)); weights.append(float(meta.get('weight', 1.0)))
        print('model', mfile, 'pred mean', round(float(preds[-1].mean()), 4), flush=True)
    w = np.array(weights) / np.sum(weights)
    if ens.get('blend', 'prob') == 'logit':
        p = expit(sum(wi * logit(np.clip(pi, 1e-6, 1 - 1e-6)) for wi, pi in zip(w, preds)))
    else:
        p = sum(wi * pi for wi, pi in zip(w, preds))
    p = p + float(ens.get('prob_shift', 0.0))
    # label-source-level adjustments using ONLY the row's own columns (team ids, game type, top/bottom, count); each block independent
    is_f = (test['game_type'].astype(str).values == 'F')
    is_lg = ((test['pitcher_team_id'].values == 13) | (test['batter_team_id'].values == 13)) & (~is_f)
    is_lgp = is_lg & (test['pitcher_team_id'].values == 13)
    lg_p = float(ens.get('lg_shift_p', ens.get('lg_shift', 0.0)) or 0.0); lg_o = float(ens.get('lg_shift_opp', ens.get('lg_shift', 0.0)) or 0.0); f_s = float(ens.get('f_shift', 0.0) or 0.0)
    p = p + np.where(is_lgp, lg_p, 0.0) + np.where(is_lg & ~is_lgp, lg_o, 0.0) + np.where(is_f, f_s, 0.0)
    lg_home = is_lg & (((test['top_bottom'].astype(str).values == 'T') & (test['pitcher_team_id'].values == 13)) | ((test['top_bottom'].astype(str).values == 'B') & (test['batter_team_id'].values == 13)))
    p = p + np.where(lg_home, float(ens.get('lg_shift_home', 0.0) or 0.0), 0.0) + np.where(is_lg & ~lg_home, float(ens.get('lg_shift_away', 0.0) or 0.0), 0.0)
    is_30 = (test['balls_before'].values == 3) & (test['strikes_before'].values == 0)
    p = p + np.where(is_lg & is_30, float(ens.get('lg30_shift', 0.0) or 0.0), 0.0)
    if ens.get('cold_slope') or ens.get('sharpen'):
        # Row-wise sharpening for under-confident segments defined by the row's OWN features; center is a training-data constant.
        center = logit(float(ens.get('cold_center', 0.486)))
        lastF = list(feat_cache.values())[-1]
        rules = list(ens.get('sharpen', []))
        if ens.get('cold_slope'): rules.append({'col': 'p_prior_n', 'lo': -1, 'hi': 0, 'slope': float(ens['cold_slope'])})
        lpp = logit(np.clip(p, 1e-6, 1 - 1e-6))
        for rule in rules:
            v = lastF[rule['col']].values
            mask = (v > rule['lo']) & (v <= rule['hi'])
            lpp[mask] = center + float(rule['slope']) * (lpp[mask] - center)
        p = expit(lpp)
    p = np.clip(p, 0.001, 0.999)
    pred_map = dict(zip(test[ID_COL].values, p))
    out = sub[[ID_COL]].copy()
    fill_const = float(stats['L_all'].loc[stats['L_all'].index.max()])  # training-data constant (no test-set dependence)
    out[TARGET_COL] = out[ID_COL].map(pred_map).fillna(fill_const).astype(float)
    os.makedirs(OUT_DIR, exist_ok=True)
    out.to_csv(os.path.join(OUT_DIR, 'submission.csv'), index=False, encoding='utf-8')
    print('saved', os.path.join(OUT_DIR, 'submission.csv'), out.shape, 'mean', round(float(out[TARGET_COL].mean()), 4))


if __name__ == '__main__':
    main()
