"""Assemble submit/script.py by inlining feature modules (single source of truth in src/), then zip."""
import os, re, sys, zipfile
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'src'); SUB = os.path.join(ROOT, 'submit')

def strip_imports(code, names):
    out = []
    for line in code.splitlines():
        if any(re.match(rf'^\s*from {n} import', line) or re.match(rf'^\s*import {n}\b', line) for n in names):
            continue
        out.append(line)
    return '\n'.join(out)

feat1 = open(os.path.join(SRC, 'features.py')).read()
feat2 = open(os.path.join(SRC, 'features2.py')).read()
feat2 = re.sub(r'from features import \([^)]*\)', '', feat2, flags=re.S)
feat2 = strip_imports(feat2, ['features', 'trackman_feats'])
# features2 defines build_stats/build_features with same names -> rename v1 references
feat2 = feat2.replace('build_stats_v1', 'build_stats_v1').replace('build_features_v1', 'build_features_v1')
feat1 = feat1.replace('def build_stats(', 'def build_stats_v1(').replace('def build_features(', 'def build_features_v1(')
nncore = open(os.path.join(SRC, 'nn_core.py')).read()
bayes = strip_imports(open(os.path.join(SRC, 'bayes_level.py')).read(), ['numpy', 'pandas', 'sys', 'os', 'warnings'])
bayes = bayes.split("if __name__ == '__main__':")[0]
fdev = open(os.path.join(SRC, 'features_dev.py')).read()
fdev = re.sub(r'from bayes_level import [^\n]*\n', '', fdev)
fdev = strip_imports(fdev, ['numpy', 'pandas'])
tmf = open(os.path.join(SRC, 'trackman_feats.py')).read()
tmf = strip_imports(tmf, ['common', 'os', 'numpy', 'pandas'])
infer = open(os.path.join(SRC, 'infer_template.py')).read()
header = '# Auto-generated by src/build_submit.py — do not edit by hand.\nimport os, sys, json, warnings\nwarnings.filterwarnings("ignore")\nimport numpy as np\nimport pandas as pd\nimport joblib\nimport lightgbm as lgb\nfrom scipy.special import expit, logit, softmax\n'
code = header + '\n# ===== features.py =====\n' + strip_imports(feat1, ['numpy', 'pandas']) + '\n# ===== trackman_feats.py =====\n' + tmf + '\n# ===== features2.py =====\n' + strip_imports(feat2, ['numpy', 'pandas']) + '\n# ===== bayes_level.py =====\n' + bayes + '\n# ===== features_dev.py =====\n' + fdev + '\n# ===== nn_core.py =====\n' + strip_imports(nncore, ['numpy', 'pandas']) + '\n# ===== inference =====\n' + infer
open(os.path.join(SUB, 'script.py'), 'w').write(code)
import json as _json
_ens = _json.load(open(os.path.join(SUB, 'model', 'ensemble.json')))
_types = {_json.load(open(os.path.join(SUB, 'model', m))).get('type') for m in _ens['models']}
reqs = ['lightgbm==4.7.0']
if 'cat' in _types or 'cat_mc' in _types: reqs.append('catboost==1.2.10')
open(os.path.join(SUB, 'requirements.txt'), 'w').write('\n'.join(reqs) + '\n')
zp = os.path.join(ROOT, 'submit.zip')
if os.path.exists(zp): os.remove(zp)
with zipfile.ZipFile(zp, 'w', zipfile.ZIP_DEFLATED) as z:
    z.write(os.path.join(SUB, 'script.py'), 'script.py')
    z.write(os.path.join(SUB, 'requirements.txt'), 'requirements.txt')
    import json
    ens = json.load(open(os.path.join(SUB, 'model', 'ensemble.json')))
    keep = {'ensemble.json', 'stats.pkl'}
    for mf in ens['models']:
        meta = json.load(open(os.path.join(SUB, 'model', mf)))
        keep.add(mf); keep.update(meta['boosters'])
        if meta.get('prep'): keep.add(meta['prep'])
    for f in sorted(keep):
        z.write(os.path.join(SUB, 'model', f), 'model/' + f)
    print('model files:', sorted(keep))
print('wrote', zp, round(os.path.getsize(zp) / 1e6, 1), 'MB')
